auto: true

#markdown: rdiscount
highlighter: 'rouge'
#paginate: 8
permalink: /:title

title: zhaosanmusi
url: "http://localhost:4000"
feed: /atom.xml
#author_info: <a href="http://mukosame.github.io/">Mukosame</a>
